import React from "react"
import Head from 'next/head'

function Head(){

    return (
        <>
        <title>Next.js 14 | Blog</title>
        <meta name="description" content="Generated by create nex app" />
        <link rel="icon" href="/favicon.ico" />
        
        </>
    );
}
export default Head;